fast-coffee/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
App::register('Gloudemans\Shoppingcart\ShoppingcartServiceProvider');

Route::get('/', 'UserController@index');
Route::get('/login','SessionController@create');
Route::get('/register','RegisterController@create');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::prefix('admin')->group(function(){
    Route::get('/login','Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login','Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
});

Route::resource('shops','ShopController');
Route::resource('menus','MenuController');
Route::resource('cart','CartController');
Route::resource('ship','ShipController');
Route::resource('search','SearchController');
Route::get('/search','SearchController@create');
Route::get('/menus/show/{id}','MenuController@show');
Route::get('/cart/{id}','CartController@create');

fast-coffee/resources/views/inc/_message.blade.php
@if (Session::has('successful'))

  <div class="alert alert-success" role="alert">
    <strong>Success:</strong> {{ Session::get('successful')}}
  </div>

@endif

fast-coffee/resources/views/inc/_messages.blade.php
@if (Session::has('success'))

  <div class="alert alert-success" role="alert">
    <strong>Success:</strong> {{ Session::get('success')}}
  </div>

@endif

fast-coffee/resources/views/inc/footer.blade.php
<div class="footer">
  <address>
    Product Listing Policy - Intellectual Property Protection - Privacy Policy - Terms of Use - Law Enforcement Compliance Guide
    © 1999-2017 Alibaba.com. All rights reserved.
  </address>
</div>

fast-coffee/resources/views/inc/form.blade.php
<center><h2>Order Table</h2></center>
<form class="form-horizontal" action="#">
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <div class="form-group group-form">
        <label class="control-label col-sm-2">Name:</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" id="name" placeholder="Enter your name" name="name">
        </div>
      </div>

      <div class="form-group group-form">
        <label class="control-label col-sm-2">Phone:</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" id="phone" placeholder="Enter your phone" name="phone">
        </div>
      </div>

      <div class="form-group group-form">
        <label class="control-label col-sm-2">Address:</label>
        <div class="col-sm-10">
          <input type="text" class="form-control" id="address" placeholder="Enter your address" name="addressname">
        </div>
      </div>

      <div class="form-group group-form">
        <label class="control-label col-sm-2">Date:</label>
        <div class="col-sm-10">
          <input type="date" class="form-control" id="date" name="date">
        </div>
      </div>

      <div class="form-group group-form">
        <label class="control-label col-sm-2">Time:</label>
        <div class="col-sm-10">
          <input type="time" class="form-control" id="time" name="time">
        </div>
      </div>

    </div>
    <div class="col-md-4"></div>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>No.</th>
          <th>Coffee name</th>
          <th>Quantity</th>
          <th>Price</th>
          <th>Sale</th>
          <th>Total</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="order-button">
    <button type="submit" class="btn btn-primary">Order</button>
  </div>
</form>

fast-coffee/resources/views/inc/navbar.blade.php
<div class="flipkart-navbar navbar-fix">
  <div class="container">
    <div class="row row1">
      <ul class="pull-right">
        <li class="upper-links active"><a class="links" href="/">Home</a></li>
        <li class="upper-links"><a class="links" href="#">Shop</a></li>
        <li class="upper-links"><a class="links" href="#">Blog</a></li>
        <li class="upper-links"><a class="links" href="#">About</a></li>
        @if (Auth::guest())
          <li class="upper-links"><a class="links" href="{{ route('login') }}">Login</a></li>
          <li class="upper-links"><a class="links" href="{{ route('register') }}">Register</a></li>
        @else
        <li class="dropdown upper-links">
          <a href="#" class="dropdown-toggle links" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ Auth::user()->name }} <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
              <a href="{{ route('logout') }}"
                onclick="event.preventDefault();
                  document.getElementById('logout-form').submit();">
                Logout
              </a>

              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
              </form>
            </li>
          </ul>
        </li>
        @endif
      </ul>
    </div>

    <div class="row row2">
      <div class="col-md-2"><h1 style="margin:0px;"><a class="title-header" href="/">Dn Coffee</a></h1></div>
      <div class="flipkart-navbar-search col-md-8">
        <div class="row">
          <form class="searchform cf" action="{{ route('search.create') }}">
            <input  type="text" class="flipkart-navbar-input col-md-11" name="search" placeholder="Is it me you’re looking for?">
            <button type="submit" class="flipkart-navbar-button col-md-1"><span class="glyphicon glyphicon-search"></span></button>
          </form>
        </div>
      </div>

      <div class="cart col-md-2">
        <a class="cart-button" href="{{route('cart.index')}}">
          <i class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></i> Cart
          <span class="item-number ">{{ Cart::count()}}</span>
        </a>
      </div>
    </div>
  </div>
</div>
@yield('content')

fast-coffee/resources/views/inc/searchbar.blade.php
<form class="navbar-form navbar-default search-form" role="search">
  <div class="form-group">
    <input type="text" class="form-control search-bar" placeholder="Enter name's shop">
    <input type="text" class="form-control search-bar" placeholder="Enter food or drink">
  </div>
  <button type="submit" class="btn btn-primary">Search</button>
</form>

fast-coffee/resources/views/inc/slide.blade.php
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
    <li data-target="#myCarousel" data-slide-to="4"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <img src="/images/banner-inner.jpg" alt="Dn Coffee">
    </div>

    <div class="item">
      <img src="/images/slide-categoryCoffee.jpg" alt="Dn Coffee">
    </div>

    <div class="item">
      <img src="/images/slide-coffeeSpoon.jpg" alt="Dn Coffee">
    </div>

    <div class="item">
      <img src="/images/banner.jpg" alt="Dn Coffee">
    </div>

    <div class="item">
      <img src="/images/banners.jpg" alt="Dn Coffee">
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

fast-coffee/resources/views/inc/thumnails.blade.php
<section class="row products">
  <div class="col-xs-6 col-md-3">
    <div class="thumbnail">
      <a href="#">
        <img src="/images/capuchino.png" alt="...">
      </a>
      <div class="caption">
        <a href="#">
          <p>Capuchino</p>
          <p>125,000 Vnd</p>
        </a>
        <a href="#">
          <button type="submit" class="btn btn-danger"><strong>+</strong></button>
        </a>
      </div>
    </div>
  </div>

  <div class="col-xs-6 col-md-3">
    <div class="thumbnail">
      <a href="#">
        <img src="/images/coffee-egg.jpeg" alt="...">
      </a>
      <div class="caption">
        <a href="#">
          <p>Capuchino</p>
          <p>125,000 Vnd</p>
        </a>
        <a href="#">
          <button type="submit" class="btn btn-danger"><strong>+</strong></button>
        </a>
      </div>
    </div>
  </div>

  <div class="col-xs-6 col-md-3">
    <div class="thumbnail">
      <a href="#">
        <img src="/images/cf-tall.jpg" alt="...">
      </a>
      <div class="caption">
        <a href="#">
          <p>Capuchino</p>
          <p>125,000 Vnd</p>
        </a>
        <a href="#">
          <button type="submit" class="btn btn-danger"><strong>+</strong></button>
        </a>
      </div>
    </div>
  </div>

  <div class="col-xs-6 col-md-3">
    <div class="thumbnail">
      <a href="#">
        <img src="/images/cotta.jpg" alt="...">
      </a>
      <div class="caption">
        <a href="#">
          <p>Capuchino</p>
          <p>125,000 Vnd</p>
        </a>
        <a href="#">
          <button type="submit" class="btn btn-danger"><strong>+</strong></button>
        </a>
      </div>
    </div>
  </div>

  <div class="col-xs-6 col-md-3">
    <div class="thumbnail">
      <a href="#">
        <img src="/images/coffee-cotta.jpg" alt="...">
      </a>
    <div class="caption">
      <a href="#">
        <p>Capuchino</p>
        <p>125,000 Vnd</p>
      </a>
      <a href="#">
        <button type="submit" class="btn btn-danger"><strong>+</strong></button>
      </a>
    </div>
  </div>
</div>

  <div class="col-xs-6 col-md-3">
    <div class="thumbnail">
      <a href="#">
        <img src="/images/cotta-love.jpg" alt="...">
      </a>
      <div class="caption">
        <a href="#">
          <p>Capuchino</p>
          <p>125,000 Vnd</p>
        </a>
        <a href="#">
          <button type="submit" class="btn btn-danger"><strong>+</strong></button>
        </a>
      </div>
    </div>
  </div>

  <div class="col-xs-6 col-md-3">
    <div class="thumbnail">
      <a href="#">
        <img src="/images/cota-cf.png" alt="...">
      </a>
      <div class="caption">
        <a href="#">
          <p>Capuchino</p>
          <p>125,000 Vnd</p>
        </a>
        <a href="#">
          <button type="submit" class="btn btn-danger"><strong>+</strong></button>
        </a>
      </div>
    </div>
  </div>

  <div class="col-xs-6 col-md-3">
    <div class="thumbnail">
      <a href="#">
        <img src="/images/mocha.jpg" alt="...">
      </a>
      <div class="caption">
        <a href="#">
          <p>Capuchino</p>
          <p>125,000 Vnd</p>
        </a>
        <a href="#">
          <button type="submit" class="btn btn-danger"><strong>+</strong></button>
        </a>
      </div>
    </div>
  </div>
</section>