fast-coffee/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
App::register('Gloudemans\Shoppingcart\ShoppingcartServiceProvider');

Route::get('/', 'UserController@index');
Route::get('/login','SessionController@create');
Route::get('/register','RegisterController@create');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::prefix('admin')->group(function(){
    Route::get('/login','Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login','Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
});

Route::resource('shops','ShopController');
Route::resource('menus','MenuController');
Route::resource('cart','CartController');
Route::resource('ship','ShipController');
Route::resource('search','SearchController');
Route::get('/search','SearchController@create');
Route::get('/menus/show/{id}','MenuController@show');
Route::get('/cart/{id}','CartController@create');

fast-coffee/app/Menu.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    protected $table = 'menus';
	public function shop() {
		return $this->belongsTo('App\Shop');
	}
}

fast-coffee/app/Http/Controllers/MenuController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Menu;
use App\Shop;
use Session;
use Intervention\Image\ImageManagerStatic as Image;

class MenuController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
		$menus = Menu::all();
		return view('menus.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $shops = Shop::all();
		return view('menus.create')->withShops($shops);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request,array(
			'name' => 'required|Max:255',
			'price' => 'required',
			'status' => 'required|Max:15',
			'description' => 'required'
		));

		// store in the database
		$menu = new Menu;

		$menu->name = $request->name;
		$menu->shop_id = $request->shop_id;
		$menu->price = $request->price;
		$menu->status = $request->status;
		$menu->description = $request->description;


		if ($request->hasFile('image')) {
			$image = $request->file('image');
			$filename = time() . '.' . $image->getClientOriginalExtension();
			$location = public_path('images/' . $filename);

			Image::make($image)->resize(800, 400)->save($location);

		}

		$menu->image = 'images/' . $filename;
		$menu->save();
		return redirect()->route('menus.create');
		 Session::flash('successful', 'The product was successfully save!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
		$menus = Menu::find($id);
        return \View::make('menus.show', compact('menus'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

fast-coffee/resources/views/menus/create.blade.php
@extends('layouts.app')

@section('Name','|Add Product')
  {!! Html::style('css/parsley.css') !!}
@section('content')

  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h2>Add Product</h2>
      <hr>
      {!! Form::open(array('route' => 'menus.store', 'data-parsley-validate' => '', 'files' => true)) !!}
        {{ Form::label('name','Name product:') }}
        {{ Form::text('name',null,array('class'=>'form-control', 'required' => '')) }}

        {{ Form::label('price','Price:') }}
        {{ Form::text('price',null,array('class'=>'form-control', 'required' => '')) }}

        {{ Form::label('status','Status:') }}
        {{ Form::text('status',null,array('class'=>'form-control', 'required' => '', 'maxlength' => '15')) }}

        {{ Form::label('shop_id', 'Shop:') }}
          <select name="shop_id" class="form-control">
            @foreach($shops as $shop)
              <option value='{{ $shop->id }}'>{{ $shop->name }}</option>
            @endforeach
          </select>

        {{ Form::label('image','Upload image product:') }}
        {{ Form::file('image') }}

        {{ Form::label('description','Description:') }}
        {{ Form::textarea('description',null,array('class'=>'form-control', 'required' => '')) }}

        {{Form::submit('Add product',array('class' => 'btn btn-success btn-lg btn-block', 'style' => 'margin-top:20px'))}}

      {!! Form::close() !!}
    </div>
  </div>

@endsection
{!! Html::script('js/parsley.min.js') !!}

fast-coffee/resources/views/menus/index.blade.php
<div class="container">
  <section class="row products">
    <?php $menus = DB::table('menus')->paginate(12); ?>
    @foreach($menus as $menu)
    <div class="col-xs-6 col-md-3">
      <div class="thumbnail">
        <a href="{{ url('menus/show/'.$menu->id) }}">
          <img src="/{{ $menu->image }}" alt="...">
        </a>
        <div class="caption">
          <a href="{{ url('menus/show/'.$menu->id) }}">
            <p>{{ $menu->name }}</p>
            <p><em>${{ $menu->price }}</em> </p>
          </a>
          <a href="{{ route('cart.edit',$menu->id) }}">
            <button class="add-to-cart" type="submit">Add to cart</button>
          </a>

        </div>
      </div>
    </div>
    @endforeach
  </section>
  <div class="pagination pull-right">
  {!! $menus->links() !!}
  </div>
</div>

fast-coffee/resources/views/menus/result.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
@if(isset($details))
  <section class="row products">
    @foreach($details as $menu)
    <div class="col-xs-6 col-md-3">
      <div class="thumbnail">
        <a href="{{ url('menus/show/'.$menu->id) }}">
          <img src="/{{ $menu->image }}" alt="...">
        </a>
        <div class="caption">
          <a href="{{ url('menus/show/'.$menu->id) }}">
            <p>{{ $menu->name }}</p>
            <p><em>${{ $menu->price }}</em> </p>
          </a>
          <a href="{{ route('cart.edit',$menu->id) }}">
            <button class="add-to-cart" type="submit">Add to cart</button>
          </a>
        </div>
      </div>
    </div>
    @endforeach
  </section>
  @endif
   <div class="pagination pull-right">
  {!! $details->links() !!}
  </div>
</div>
@endsection

fast-coffee/resources/views/menus/show.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Dn Coffee</title>
	<link rel="stylesheet" href="/css/app.css">
	<link rel="stylesheet" href="/css/custom.css">
  <link rel="stylesheet" href="/css/parsley.css">
</head>
<body>
	<header>
	  @include('inc.navbar')
 	</header>
<div class="container">
    <div class="title-products">
      <h2>{{ $menus->name }}</h2>
      <hr>
    </div>
    <div class="infor-products">
    <div class="row">
      <div class="col-md-4">
        <div class="show-image">
          <a href="#">
            <image src="/{{ $menus->image }}" class="img-thumbnail"></image>
          </a>
        </div>
      </div>
      <div class="col-md-8">
        <table class="table table-border">
          <tr>
            <td>Product name:</td>
            <td>{{ $menus->name }}</td>
          </tr>
          <tr>
            <td>Price:</td>
            <td>{{ $menus->price }}</td>
          </tr>
          <tr>
            <td>suplier:</td>
            <td>{{ $menus->shop['name'] }}</td>
          </tr>
          <tr>
            <td>Address:</td>
            <td>{{ $menus->shop['address'] }}</td>
          </tr>
        </table>
        <a href="{{ route('cart.create',[$menus->id]) }}" class="btn btn-success btn-sm">Proceed to Checkout</a>
        <a href="{{ route('cart.edit',$menus->id) }}" class="btn btn-danger btn-sm">Add to cart</a>
      </div>
    </div>
    </div>
    <hr>
    <div class="desc-products">
      <h4>Description</h4>
      {{ $menus->description }}
    </div>
</div>
 	<footer>
  	@include('inc.footer')
 	</footer>
   <script type="" src="/js/jquery.min.js"></script>
	 <script type="" src="/js/bootstrap.min.js"></script>
   <script type="" src="/js/parsley.min.js"></script>
</body>
</html>